# -*- coding: utf-8 -*-
"""calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZB1sDodbsVBXNFT1V3X2zUFctEpbGPJD
"""

def calculadora():
  """Função para realizar operações matemáticas básicas."""

  while True:
    print("\nEscolha a operação:")
    print("1. Soma")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Sair")

    opcao = input("Digite o número da operação desejada: ")

    if opcao == '5':
      print("Saindo da calculadora...")
      break

    try:
      num1 = float(input("Digite o primeiro número: "))
      num2 = float(input("Digite o segundo número: "))
    except ValueError:
      print("Entrada inválida. Por favor, digite números.")
      continue

    if opcao == '1':
      resultado = num1 + num2
      print(f"Resultado: {resultado}")
    elif opcao == '2':
      resultado = num1 - num2
      print(f"Resultado: {resultado}")
    elif opcao == '3':
      resultado = num1 * num2
      print(f"Resultado: {resultado}")
    elif opcao == '4':
      if num2 == 0:
        print("Erro: Divisão por zero.")
      else:
        resultado = num1 / num2
        print(f"Resultado: {resultado}")
    else:
      print("Opção inválida. Por favor, escolha uma operação válida.")

if __name__ == "__main__":
  calculadora()